import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MuiCssProvider from "./MuiCssProvider";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JD - Portfolio",
  description: "Generated by create next app",  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MuiCssProvider>
          <NavBar />
          {children}
        </MuiCssProvider>
      </body>
    </html>
  );
}
